export enum EntityNames {
  User = "user",
  UserOtp = "user_otp",
  UserAddress = "user_address",
  Category = "category",
  Supplier = "supplier",
  SupplierOtp = "supplier_otp",
  MenuType = "menu-type",
  Menu = "menu",
  MenuItem = "menu_item",
  Feedbacks = "feedback",
  Type = "type",
  UserBasket = "user-basket",
  Discount = "discount",
  Order = "order",
  OrderItem = "order-item",
  Payment = "payment",
}
